/**
 * Bilingual (English / Hindi) copy for the "Inside the app" feature suite.
 * Mirrors real features of the Medhee mobile app (medisafe-mobile):
 * live doctor consults, AI voice nurse, prescription scan, lab report chat,
 * and family profiles. The app itself ships English + Hindi.
 */

export type Lang = 'en' | 'hi';
export type FeatureKey = 'consult' | 'nurse' | 'scan' | 'report' | 'family';
export type DoctorId = 'd1' | 'd2' | 'd3';
export type MemberId = 'me' | 'mom' | 'papa' | 'kid';
export type Scenario = 'normal' | 'emergency';
export type LabStatus = 'low' | 'high' | 'normal';

export interface ScriptLine {
  from: 'nurse' | 'you';
  text: string;
}

/** Replace `{key}` placeholders in a string. */
export function fmt(template: string, vars: Record<string, string | number>): string {
  return template.replace(/\{(\w+)\}/g, (_, key: string) => String(vars[key] ?? `{${key}}`));
}

const en = {
  suite: {
    eyebrow: 'App features',
    title: 'Help for the days you feel unwell',
    subtitle: 'Five things the Medhee app does today. You can try each one below, in English or Hindi.',
    langLabel: 'Language',
    tryHint: 'Interactive demo',
    available: 'Available in the app',
    howToTry: 'Try it',
    demoLabel: 'Interactive app demo',
  },
  tabs: {
    consult: { label: 'Talk to a Doctor', short: 'Video · Voice · Chat' },
    nurse: { label: 'AI Nurse', short: 'Speak your symptoms' },
    scan: { label: 'Scan Prescription', short: 'From a photo' },
    report: { label: 'Lab Report Chat', short: 'Ask your report' },
    family: { label: 'Family Profiles', short: 'Parents, kids, anyone' },
  },
  info: {
    consult: {
      title: 'Consult a doctor in the app',
      body: "Pick a doctor who is available and talk by video, voice or chat inside the app. Your medicines, allergies and reports reach the doctor before the call starts, so you don't have to explain your history again.",
      points: [
        'Video, voice or chat, whichever you prefer',
        'The doctor sees your full health context before the call begins',
        'Doctors join from the Medhee doctor app with a live patient queue',
      ],
      try: 'Tap an available doctor, then pick video, voice or chat.',
    },
    nurse: {
      title: "Tell the AI nurse what's wrong",
      body: "Talk to Medhee's AI nurse like you would talk to a nurse at a clinic. It asks follow-up questions, checks your history and tells you how urgent it is, in English or Hindi. If you'd rather type, the same check works as a chat.",
      points: [
        'Real-time voice conversation',
        'Follow-up questions and a severity assessment',
        'Emergency warning signs are flagged immediately',
      ],
      try: 'Pick a symptom and tap “Connect to AI Nurse”.',
    },
    scan: {
      title: 'Add medicines from a prescription photo',
      body: 'Take a photo of a prescription. Medhee reads the medicine names, matches them to its medicine database and adds them to your schedule.',
      points: [
        'Scan with your camera or pick a photo from the gallery',
        'Medicines matched automatically, with manual search as a backup',
        'New medicines are checked against what you already take',
      ],
      try: 'Tap “Scan with camera” to read the sample prescription.',
    },
    report: {
      title: 'Ask questions about your lab report',
      body: 'Upload a PDF or photo of a lab report. Medhee pulls out each value, marks the ones outside the normal range, and answers your questions in plain language.',
      points: [
        'Values extracted and flagged automatically',
        'Ask anything: “Are my values normal?”, “What should I eat?”',
        'Reports stay in your health record for every future consult',
      ],
      try: 'Upload the sample report, then tap a question.',
    },
    family: {
      title: "Look after your family's medicines too",
      body: "Add your parents, children or anyone you look after. Switch profiles to manage each person's medicines, doses and reports. Useful if you already handle your parents' medicines.",
      points: [
        'A separate health profile for every family member',
        'Track medicines and doses for each person',
        'Switch profiles in one tap',
      ],
      try: 'Switch between family members or add a new one.',
    },
  },
  consult: {
    header: 'Consult a doctor',
    sub: 'Doctors available now',
    sharedNote: 'Your health profile is shared only with the doctor you choose',
    pickHint: 'Tap an available doctor to start',
    available: 'Available',
    busy: 'Busy',
    doctors: {
      d1: { name: 'Dr. Ananya Rao', spec: 'General Physician' },
      d2: { name: 'Dr. Vikram Shah', spec: 'Diabetologist' },
      d3: { name: 'Dr. Meera Iyer', spec: 'Dermatologist' },
    } as Record<DoctorId, { name: string; spec: string }>,
    chooseMode: 'How would you like to consult?',
    modes: {
      video: { label: 'Video call', desc: 'Face-to-face with the doctor' },
      voice: { label: 'Voice call', desc: 'Audio only' },
      chat: { label: 'Chat', desc: 'Type at your own pace' },
    },
    cancel: 'Cancel',
    waiting: 'Waiting for {name} to accept…',
    sharedContext: 'Your health profile has been shared securely',
    doctorSees: 'Doctor can see',
    contextChips: ['Metformin 500mg', 'Penicillin allergy', 'HbA1c 6.8%'],
    connected: 'Connected',
    you: 'You',
    cameraOff: 'Camera off',
    mute: 'Mute',
    unmute: 'Unmute',
    camera: 'Camera',
    speaker: 'Speaker',
    end: 'End',
    chatGreeting: "Hi, I'm {name}. I can see your medicines and recent reports. What's troubling you today?",
    chatReplies: [
      'Thanks for sharing. How long has this been going on?',
      'Okay. Keep taking your Metformin after meals and drink plenty of water.',
      "If it doesn't improve in 2 days, please book a follow-up with me.",
    ],
    chatQuick: ['I have a stomach ache', 'Since this morning', 'Okay, thank you'],
    chatPlaceholder: 'Type a message…',
    send: 'Send message',
    typing: 'typing…',
    ended: 'Consultation complete',
    endedSub: 'Your consultation is saved to your history.',
    rate: 'Rate your consultation',
    star: '{n} star rating',
    thanks: 'Thanks for your feedback!',
    back: 'Back to doctors',
  },
  nurse: {
    title: 'AI Nurse',
    idle: 'Tap to start speaking with the AI nurse',
    scenarioLabel: 'Pick a symptom to try',
    scenarios: { normal: 'Fever & headache', emergency: 'Sudden severe headache' } as Record<Scenario, string>,
    connect: 'Connect to AI Nurse',
    connecting: 'Setting up your AI nurse session…',
    listening: 'Listening…',
    speaking: 'AI nurse is speaking…',
    nurseLabel: 'AI Nurse',
    youLabel: 'You',
    scripts: {
      normal: [
        { from: 'nurse', text: "Hi! I'm your AI nurse. What's bothering you today?" },
        { from: 'you', text: "I've had a headache and mild fever since yesterday." },
        { from: 'nurse', text: 'How high is the fever? Any neck stiffness or rash?' },
        { from: 'you', text: 'About 100°F. No stiffness, no rash.' },
        { from: 'nurse', text: 'Are you taking any medicine for it right now?' },
        { from: 'you', text: 'Just paracetamol.' },
      ],
      emergency: [
        { from: 'nurse', text: "Hi! I'm your AI nurse. What's bothering you today?" },
        { from: 'you', text: 'I suddenly have the worst headache of my life.' },
        { from: 'nurse', text: 'That can be a sign of a medical emergency. Please get help right away.' },
      ],
    } as Record<Scenario, ScriptLine[]>,
    resultNormal: {
      title: 'Assessment',
      level: 'Low to moderate',
      points: [
        'Rest, fluids and paracetamol as directed',
        'Paracetamol is fine with your current medicines',
        'See a doctor if the fever lasts over 3 days or goes above 103°F',
      ],
      cta: 'Talk to a doctor',
    },
    resultEmergency: {
      title: 'Possible emergency',
      body: 'A sudden, severe headache needs urgent care. Call 112 or go to the nearest emergency room now.',
      cta: 'Call 112',
      demoNote: 'Demo only',
    },
    saved: 'Saved to your assessments',
    restart: 'Start over',
    end: 'End session',
    disclaimer: 'AI guidance only. Not a diagnosis.',
  },
  scan: {
    title: 'Scan prescription',
    hint: 'Point your camera at a prescription or pick a photo',
    scanBtn: 'Scan with camera',
    galleryBtn: 'Choose from gallery',
    scanning: 'Reading your prescription…',
    found: '{n} medicines found',
    review: 'Review and add to your medicines',
    meds: [
      { name: 'Pantoprazole 40mg', dose: '1 tablet · before breakfast' },
      { name: 'Domperidone 10mg', dose: '1 tablet · before meals' },
      { name: 'Cetirizine 10mg', dose: '1 tablet · at night' },
    ],
    add: 'Add {n} to my medicines',
    selectAtLeast: 'Select at least one medicine',
    added: 'Added to your medicines',
    addedSub: 'Medhee suggested timings and checked them against your current medicines.',
    safe: 'No severe interactions found',
    again: 'Scan another',
    rx: { clinic: 'City Care Clinic', patient: 'Patient: Rahul S.', date: '12/09/2026', sign: 'Dr. signature' },
  },
  report: {
    uploadTitle: 'Upload a lab report',
    uploadSub: 'PDF or photo of any lab report',
    uploadBtn: 'Upload sample report',
    processing: 'Extracting your values…',
    reportName: 'Blood test · CBC, Lipid, Vitamin D, Thyroid',
    values: [
      { name: 'Haemoglobin', value: '12.1 g/dL', status: 'low' },
      { name: 'LDL Cholesterol', value: '148 mg/dL', status: 'high' },
      { name: 'Vitamin D', value: '18 ng/mL', status: 'low' },
      { name: 'TSH', value: '2.1 mIU/L', status: 'normal' },
    ] as { name: string; value: string; status: LabStatus }[],
    status: { low: 'Low', high: 'High', normal: 'Normal' } as Record<LabStatus, string>,
    askTitle: 'Ask about your report',
    suggestions: [
      'Explain in simple terms',
      'Any concerns in this report?',
      'What should I ask my doctor?',
      'Are my lab values normal?',
      'What foods should I eat or avoid?',
    ],
    answers: [
      "Most of your values are in the normal range. Three stand out: haemoglobin is slightly low, LDL ('bad') cholesterol is high, and vitamin D is low. None of these is an emergency, but they're worth discussing with your doctor.",
      'The main things to follow up: LDL cholesterol at 148 mg/dL (target is under 100), vitamin D at 18 ng/mL (deficient range), and haemoglobin at 12.1 g/dL (slightly low).',
      '• Do I need medicine for my LDL, or should I try diet changes first?\n• Should I take a vitamin D supplement, and how much?\n• Could my low haemoglobin be iron deficiency?\n• When should I repeat these tests?',
      'Normal: TSH 2.1 mIU/L. Outside the normal range: haemoglobin (low), LDL cholesterol (high) and vitamin D (low).',
      'Eat more: oats, dals, leafy greens, nuts and eggs. Cut down on: fried snacks, sweets and full-fat dairy. For iron, try spinach, chana and rajma; for vitamin D, morning sunlight and fortified milk.',
    ],
    fallback:
      "Good question. In your report, LDL cholesterol and vitamin D need the most attention. It's worth raising both with your doctor at your next visit.",
    placeholder: 'Ask about your report…',
    send: 'Send question',
    typing: 'Medhee is reading your report…',
    disclaimer: 'For information only. Check with your doctor.',
    newReport: 'Upload another',
  },
  family: {
    title: 'Family',
    viewingSelf: 'Your profile',
    viewing: "{name}'s profile",
    members: {
      me: { name: 'You', relation: 'Self' },
      mom: { name: 'Mom', relation: 'Mother' },
      papa: { name: 'Papa', relation: 'Father' },
      kid: { name: 'Aarav', relation: 'Son · 8 yrs' },
    } as Record<MemberId, { name: string; relation: string }>,
    meds: {
      me: [
        { name: 'Pantoprazole 40mg', time: '8:00 AM · before breakfast' },
        { name: 'Cetirizine 10mg', time: '9:30 PM · at night' },
      ],
      mom: [
        { name: 'Levothyroxine 50mcg', time: '6:30 AM · empty stomach' },
        { name: 'Calcium + Vitamin D3', time: '2:00 PM · after lunch' },
      ],
      papa: [
        { name: 'Amlodipine 5mg', time: '9:00 AM · after breakfast' },
        { name: 'Metformin 500mg', time: '8:30 PM · after dinner' },
        { name: 'Atorvastatin 10mg', time: '10:00 PM · at bedtime' },
      ],
      kid: [{ name: 'Paracetamol syrup 5ml', time: 'As needed · for fever' }],
    } as Record<MemberId, { name: string; time: string }[]>,
    todaysMeds: "Today's medicines",
    taken: 'Taken',
    markTaken: 'Mark taken',
    progress: '{taken}/{total} taken',
    safe: 'No severe interactions',
    noMeds: 'No medicines yet',
    noMedsSub: 'Scan a prescription to add their medicines.',
    add: 'Add member',
    addTitle: 'Add a family member',
    nameLabel: 'Name',
    namePlaceholder: 'e.g. Dadi',
    nameError: 'Please enter a name',
    relationLabel: 'Relation',
    relations: ['Mother', 'Father', 'Spouse', 'Child', 'Grandparent', 'Other'],
    save: 'Add',
    cancel: 'Cancel',
    addedToast: '{name} added to your family',
  },
};

export type Copy = typeof en;

const hi: Copy = {
  suite: {
    eyebrow: 'ऐप फ़ीचर',
    title: 'तबीयत खराब होने पर भी आपके साथ',
    subtitle: 'Medhee ऐप आज ये पाँच काम करता है। नीचे हर एक को अंग्रेज़ी या हिंदी में आज़माएँ।',
    langLabel: 'भाषा',
    tryHint: 'इंटरैक्टिव डेमो',
    available: 'ऐप में उपलब्ध',
    howToTry: 'आज़माएँ',
    demoLabel: 'इंटरैक्टिव ऐप डेमो',
  },
  tabs: {
    consult: { label: 'डॉक्टर से बात करें', short: 'वीडियो · वॉइस · चैट' },
    nurse: { label: 'AI नर्स', short: 'अपने लक्षण बोलें' },
    scan: { label: 'पर्चा स्कैन करें', short: 'फ़ोटो से दवाओं की सूची' },
    report: { label: 'लैब रिपोर्ट चैट', short: 'अपनी रिपोर्ट से पूछें' },
    family: { label: 'परिवार प्रोफ़ाइल', short: 'माता-पिता, बच्चे, सब' },
  },
  info: {
    consult: {
      title: 'ऐप में ही डॉक्टर से सलाह लें',
      body: 'उपलब्ध डॉक्टर चुनें और ऐप के अंदर ही वीडियो, वॉइस या चैट से सलाह लें। कॉल शुरू होने से पहले आपकी दवाइयाँ, एलर्जी और रिपोर्ट डॉक्टर तक पहुँच जाती हैं, इसलिए आपको अपनी हिस्ट्री दोहरानी नहीं पड़ती।',
      points: [
        'वीडियो, वॉइस या चैट, जो आपको ठीक लगे',
        'कॉल से पहले डॉक्टर आपकी पूरी हेल्थ जानकारी देखते हैं',
        'डॉक्टर Medhee डॉक्टर ऐप से लाइव मरीज़ कतार के साथ जुड़ते हैं',
      ],
      try: 'कोई उपलब्ध डॉक्टर चुनें, फिर वीडियो, वॉइस या चैट चुनें।',
    },
    nurse: {
      title: 'AI नर्स को बताइए कि क्या तकलीफ़ है',
      body: 'Medhee की AI नर्स से वैसे ही बात करें जैसे किसी असली नर्स से करते हैं। यह सुनती है, आगे के सवाल पूछती है, आपकी हिस्ट्री देखती है और बताती है कि स्थिति कितनी गंभीर है। यह अंग्रेज़ी और हिंदी दोनों में काम करती है। टाइप करना पसंद है? यही जाँच चैट में भी होती है।',
      points: [
        'रियल-टाइम वॉइस बातचीत',
        'आगे के सवाल और गंभीरता का आकलन',
        'आपातकालीन संकेत तुरंत पहचाने जाते हैं',
      ],
      try: 'एक लक्षण चुनें और “AI नर्स से जुड़ें” दबाएँ।',
    },
    scan: {
      title: 'पर्चे की फ़ोटो से दवाइयाँ जोड़ें',
      body: 'पर्चे की फ़ोटो लें। Medhee दवाइयों के नाम पढ़ता है, उन्हें अपने दवा डेटाबेस से मिलाता है और आपके शेड्यूल में जोड़ देता है।',
      points: [
        'कैमरे से स्कैन करें या गैलरी से फ़ोटो चुनें',
        'दवाइयाँ अपने-आप मिलाई जाती हैं, ज़रूरत हो तो मैन्युअल सर्च भी',
        'नई दवाइयों को आपकी मौजूदा दवाओं के साथ जाँचा जाता है',
      ],
      try: 'सैंपल पर्चा पढ़ने के लिए “कैमरे से स्कैन करें” दबाएँ।',
    },
    report: {
      title: 'अपनी लैब रिपोर्ट के बारे में सवाल पूछें',
      body: 'किसी भी लैब रिपोर्ट की PDF या फ़ोटो अपलोड करें। Medhee हर वैल्यू निकालता है, सामान्य सीमा से बाहर वाली वैल्यू को चिह्नित करता है, और आपके सवालों के जवाब आसान भाषा में देता है।',
      points: [
        'वैल्यू अपने-आप निकाली और चिह्नित की जाती हैं',
        'कुछ भी पूछें: “क्या मेरी वैल्यू सामान्य हैं?”, “मुझे क्या खाना चाहिए?”',
        'रिपोर्ट हर आगे की सलाह के लिए आपके हेल्थ रिकॉर्ड में रहती हैं',
      ],
      try: 'सैंपल रिपोर्ट अपलोड करें, फिर कोई सवाल चुनें।',
    },
    family: {
      title: 'परिवार की दवाइयाँ भी संभालें',
      body: 'अपने माता-पिता, बच्चों या जिनकी भी आप देखभाल करते हैं, उन्हें जोड़ें। हर व्यक्ति की दवाइयाँ, खुराक और रिपोर्ट संभालने के लिए प्रोफ़ाइल बदलें। अगर आप अपने माता-पिता की दवाइयाँ संभालते हैं तो यह काम आता है।',
      points: [
        'परिवार के हर सदस्य के लिए अलग हेल्थ प्रोफ़ाइल',
        'हर व्यक्ति की दवाइयों और खुराक पर नज़र',
        'एक टैप में प्रोफ़ाइल बदलें',
      ],
      try: 'परिवार के सदस्यों के बीच बदलें या नया सदस्य जोड़ें।',
    },
  },
  consult: {
    header: 'डॉक्टर से सलाह',
    sub: 'अभी उपलब्ध डॉक्टर',
    sharedNote: 'आपकी हेल्थ प्रोफ़ाइल सिर्फ़ आपके चुने हुए डॉक्टर के साथ साझा होती है',
    pickHint: 'शुरू करने के लिए कोई उपलब्ध डॉक्टर चुनें',
    available: 'उपलब्ध',
    busy: 'व्यस्त',
    doctors: {
      d1: { name: 'डॉ. अनन्या राव', spec: 'जनरल फ़िज़िशियन' },
      d2: { name: 'डॉ. विक्रम शाह', spec: 'डायबिटीज़ विशेषज्ञ' },
      d3: { name: 'डॉ. मीरा अय्यर', spec: 'त्वचा रोग विशेषज्ञ' },
    },
    chooseMode: 'आप कैसे सलाह लेना चाहेंगे?',
    modes: {
      video: { label: 'वीडियो कॉल', desc: 'डॉक्टर से आमने-सामने' },
      voice: { label: 'वॉइस कॉल', desc: 'सिर्फ़ आवाज़' },
      chat: { label: 'चैट', desc: 'अपनी सुविधा से टाइप करें' },
    },
    cancel: 'रद्द करें',
    waiting: '{name} के स्वीकार करने का इंतज़ार…',
    sharedContext: 'आपकी हेल्थ प्रोफ़ाइल सुरक्षित रूप से साझा की गई',
    doctorSees: 'डॉक्टर देख सकते हैं',
    contextChips: ['मेटफ़ॉर्मिन 500mg', 'पेनिसिलिन एलर्जी', 'HbA1c 6.8%'],
    connected: 'जुड़ गए',
    you: 'आप',
    cameraOff: 'कैमरा बंद',
    mute: 'म्यूट',
    unmute: 'अनम्यूट',
    camera: 'कैमरा',
    speaker: 'स्पीकर',
    end: 'समाप्त',
    chatGreeting: 'नमस्ते, मैं {name}। आपकी दवाइयाँ और हाल की रिपोर्ट मेरे सामने हैं। आज क्या परेशानी है?',
    chatReplies: [
      'बताने के लिए धन्यवाद। यह कब से हो रहा है?',
      'ठीक है। मेटफ़ॉर्मिन खाने के बाद ही लें और पानी खूब पिएँ।',
      'अगर 2 दिन में आराम न मिले, तो कृपया मेरे साथ फ़ॉलो-अप बुक करें।',
    ],
    chatQuick: ['मेरे पेट में दर्द है', 'आज सुबह से', 'ठीक है, धन्यवाद'],
    chatPlaceholder: 'संदेश लिखें…',
    send: 'संदेश भेजें',
    typing: 'टाइप कर रहे हैं…',
    ended: 'सलाह पूरी हुई',
    endedSub: 'आपकी सलाह आपकी हिस्ट्री में सेव हो गई है।',
    rate: 'अपनी सलाह को रेट करें',
    star: '{n} स्टार रेटिंग',
    thanks: 'आपकी प्रतिक्रिया के लिए धन्यवाद!',
    back: 'डॉक्टरों की सूची पर वापस',
  },
  nurse: {
    title: 'AI नर्स',
    idle: 'AI नर्स से बात करने के लिए दबाएं',
    scenarioLabel: 'आज़माने के लिए एक लक्षण चुनें',
    scenarios: { normal: 'बुखार और सिरदर्द', emergency: 'अचानक तेज़ सिरदर्द' },
    connect: 'AI नर्स से जुड़ें',
    connecting: 'आपका AI नर्स सेशन तैयार हो रहा है…',
    listening: 'सुन रही है…',
    speaking: 'AI नर्स बोल रही है…',
    nurseLabel: 'AI नर्स',
    youLabel: 'आप',
    scripts: {
      normal: [
        { from: 'nurse', text: 'नमस्ते! मैं आपकी AI नर्स हूँ। आज आपको क्या परेशानी है?' },
        { from: 'you', text: 'कल से मुझे सिरदर्द और हल्का बुखार है।' },
        { from: 'nurse', text: 'बुखार कितना है? क्या गर्दन में अकड़न या कोई दाने हैं?' },
        { from: 'you', text: 'लगभग 100°F। न अकड़न है, न दाने।' },
        { from: 'nurse', text: 'क्या आप अभी इसके लिए कोई दवा ले रहे हैं?' },
        { from: 'you', text: 'बस पैरासिटामोल।' },
      ],
      emergency: [
        { from: 'nurse', text: 'नमस्ते! मैं आपकी AI नर्स हूँ। आज आपको क्या परेशानी है?' },
        { from: 'you', text: 'मुझे अचानक ज़िंदगी का सबसे तेज़ सिरदर्द हो रहा है।' },
        { from: 'nurse', text: 'यह किसी मेडिकल इमरजेंसी का संकेत हो सकता है। कृपया तुरंत मदद लें।' },
      ],
    },
    resultNormal: {
      title: 'आकलन',
      level: 'कम से मध्यम',
      points: [
        'आराम करें, पानी पिएँ और बताए अनुसार पैरासिटामोल लें',
        'पैरासिटामोल आपकी मौजूदा दवाओं के साथ ठीक है',
        'अगर बुखार 3 दिन से ज़्यादा रहे या 103°F से ऊपर जाए तो डॉक्टर को दिखाएँ',
      ],
      cta: 'डॉक्टर से बात करें',
    },
    resultEmergency: {
      title: 'संभावित इमरजेंसी',
      body: 'अचानक, तेज़ सिरदर्द में तुरंत इलाज ज़रूरी है। अभी 112 पर कॉल करें या नज़दीकी इमरजेंसी में जाएँ।',
      cta: '112 पर कॉल करें',
      demoNote: 'सिर्फ़ डेमो',
    },
    saved: 'आपके असेसमेंट में सेव किया गया',
    restart: 'फिर से शुरू करें',
    end: 'सेशन समाप्त करें',
    disclaimer: 'सिर्फ़ AI मार्गदर्शन। यह निदान नहीं है।',
  },
  scan: {
    title: 'पर्चा स्कैन करें',
    hint: 'कैमरे को पर्चे पर रखें या कोई फ़ोटो चुनें',
    scanBtn: 'कैमरे से स्कैन करें',
    galleryBtn: 'गैलरी से चुनें',
    scanning: 'आपका पर्चा पढ़ा जा रहा है…',
    found: '{n} दवाइयाँ मिलीं',
    review: 'जाँचें और अपनी दवाओं में जोड़ें',
    meds: [
      { name: 'Pantoprazole 40mg', dose: '1 गोली · नाश्ते से पहले' },
      { name: 'Domperidone 10mg', dose: '1 गोली · खाने से पहले' },
      { name: 'Cetirizine 10mg', dose: '1 गोली · रात में' },
    ],
    add: '{n} दवाइयाँ जोड़ें',
    selectAtLeast: 'कम से कम एक दवा चुनें',
    added: 'आपकी दवाओं में जोड़ दी गईं',
    addedSub: 'Medhee ने समय सुझाया और इन्हें आपकी मौजूदा दवाओं के साथ जाँचा।',
    safe: 'कोई गंभीर इंटरैक्शन नहीं मिला',
    again: 'दूसरा स्कैन करें',
    rx: { clinic: 'City Care Clinic', patient: 'Patient: Rahul S.', date: '12/09/2026', sign: 'Dr. signature' },
  },
  report: {
    uploadTitle: 'लैब रिपोर्ट अपलोड करें',
    uploadSub: 'किसी भी लैब रिपोर्ट की PDF या फ़ोटो',
    uploadBtn: 'सैंपल रिपोर्ट अपलोड करें',
    processing: 'आपकी वैल्यू निकाली जा रही हैं…',
    reportName: 'ब्लड टेस्ट · CBC, लिपिड, विटामिन D, थायरॉइड',
    values: [
      { name: 'हीमोग्लोबिन', value: '12.1 g/dL', status: 'low' },
      { name: 'LDL कोलेस्ट्रॉल', value: '148 mg/dL', status: 'high' },
      { name: 'विटामिन D', value: '18 ng/mL', status: 'low' },
      { name: 'TSH', value: '2.1 mIU/L', status: 'normal' },
    ],
    status: { low: 'कम', high: 'ज़्यादा', normal: 'सामान्य' },
    askTitle: 'अपनी रिपोर्ट के बारे में पूछें',
    suggestions: [
      'आसान शब्दों में समझाइए',
      'क्या इस रिपोर्ट में कोई चिंता की बात है?',
      'मुझे डॉक्टर से क्या पूछना चाहिए?',
      'क्या मेरी लैब वैल्यू सामान्य हैं?',
      'मुझे क्या खाना चाहिए और किससे बचना चाहिए?',
    ],
    answers: [
      'आपकी ज़्यादातर वैल्यू सामान्य हैं। तीन चीज़ें ध्यान देने लायक हैं: हीमोग्लोबिन थोड़ा कम है, LDL ("खराब") कोलेस्ट्रॉल ज़्यादा है, और विटामिन D कम है। इनमें से कोई भी इमरजेंसी नहीं है, पर डॉक्टर से बात ज़रूर करें।',
      'मुख्य बातें: LDL कोलेस्ट्रॉल 148 mg/dL (100 से कम होना चाहिए), विटामिन D 18 ng/mL (कमी की श्रेणी में), और हीमोग्लोबिन 12.1 g/dL (थोड़ा कम)।',
      '• क्या LDL के लिए दवा चाहिए या पहले खान-पान बदलूँ?\n• क्या मुझे विटामिन D सप्लीमेंट लेना चाहिए, और कितना?\n• क्या कम हीमोग्लोबिन आयरन की कमी से है?\n• ये टेस्ट दोबारा कब कराऊँ?',
      'सामान्य: TSH 2.1 mIU/L। सीमा से बाहर: हीमोग्लोबिन (कम), LDL कोलेस्ट्रॉल (ज़्यादा) और विटामिन D (कम)।',
      'ज़्यादा खाएँ: ओट्स, दालें, हरी पत्तेदार सब्ज़ियाँ, मेवे और अंडे। कम करें: तले हुए स्नैक्स, मिठाई और फुल-फ़ैट डेयरी। आयरन के लिए पालक, चना और राजमा; विटामिन D के लिए सुबह की धूप और फ़ोर्टिफ़ाइड दूध।',
    ],
    fallback:
      'अच्छा सवाल। आपकी रिपोर्ट में LDL कोलेस्ट्रॉल और विटामिन D पर सबसे ज़्यादा ध्यान देने की ज़रूरत है। अगली बार डॉक्टर से इन दोनों पर ज़रूर बात करें।',
    placeholder: 'अपनी रिपोर्ट के बारे में पूछें…',
    send: 'सवाल भेजें',
    typing: 'Medhee आपकी रिपोर्ट पढ़ रहा है…',
    disclaimer: 'सिर्फ़ जानकारी के लिए। डॉक्टर से पुष्टि करें।',
    newReport: 'दूसरी रिपोर्ट अपलोड करें',
  },
  family: {
    title: 'परिवार',
    viewingSelf: 'आपकी प्रोफ़ाइल',
    viewing: '{name} की प्रोफ़ाइल',
    members: {
      me: { name: 'आप', relation: 'स्वयं' },
      mom: { name: 'मम्मी', relation: 'माँ' },
      papa: { name: 'पापा', relation: 'पिता' },
      kid: { name: 'आरव', relation: 'बेटा · 8 साल' },
    },
    meds: {
      me: [
        { name: 'Pantoprazole 40mg', time: 'सुबह 8:00 · नाश्ते से पहले' },
        { name: 'Cetirizine 10mg', time: 'रात 9:30 · सोने से पहले' },
      ],
      mom: [
        { name: 'Levothyroxine 50mcg', time: 'सुबह 6:30 · खाली पेट' },
        { name: 'Calcium + Vitamin D3', time: 'दोपहर 2:00 · खाने के बाद' },
      ],
      papa: [
        { name: 'Amlodipine 5mg', time: 'सुबह 9:00 · नाश्ते के बाद' },
        { name: 'Metformin 500mg', time: 'रात 8:30 · खाने के बाद' },
        { name: 'Atorvastatin 10mg', time: 'रात 10:00 · सोते समय' },
      ],
      kid: [{ name: 'Paracetamol syrup 5ml', time: 'ज़रूरत पर · बुखार में' }],
    },
    todaysMeds: 'आज की दवाइयाँ',
    taken: 'ली गई',
    markTaken: 'ले ली',
    progress: '{taken}/{total} ली गईं',
    safe: 'कोई गंभीर इंटरैक्शन नहीं',
    noMeds: 'अभी कोई दवा नहीं',
    noMedsSub: 'इनकी दवाइयाँ जोड़ने के लिए पर्चा स्कैन करें।',
    add: 'सदस्य जोड़ें',
    addTitle: 'परिवार का सदस्य जोड़ें',
    nameLabel: 'नाम',
    namePlaceholder: 'जैसे: दादी',
    nameError: 'कृपया नाम लिखें',
    relationLabel: 'रिश्ता',
    relations: ['माँ', 'पिता', 'पति/पत्नी', 'बच्चा', 'दादा-दादी / नाना-नानी', 'अन्य'],
    save: 'जोड़ें',
    cancel: 'रद्द करें',
    addedToast: '{name} को परिवार में जोड़ा गया',
  },
};

export const COPY: Record<Lang, Copy> = { en, hi };
